services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env.production
    environment:
      - HUSKY=0
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
