# syntax=docker/dockerfile:1

ARG NODE_VERSION=22.12.0

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

COPY package*.json ./

# Install all dependencies including devDependencies
RUN npm install

# Set NODE_ENV to development
ENV NODE_ENV=development

EXPOSE 8000

# Use nodemon for development to watch for changes
CMD ["npm", "run", "dev"]